[package]
name = "wasmlite"
version = "0.0.1"
authors = ["Steve Akinyemi <appcypher@outlook.com>"]
edition = "2018"
#-----------------------------------------
description = "An embeddable WebAssembly virtual machine"
readme = "README.md"
repository = "https://github.com/appcypher/wasmlite"
keywords = ["compiler", "webassembly", "vm", "runtime", "llvm"]
categories = ["development-tools", "parser-implementations", "wasm"]
documentation = "https://github.com/appcypher/wasmlite"
homepage = "https://github.com/appcypher/wasmlite"
license = "Apache-2.0"

[dependencies]
wasmlite-parser = { path = "lib/parser" }
wasmlite-llvm = { path = "lib/llvm" }
wasmlite-utils = { path = "lib/utils" }
wabt = "0.7.4" # Only there for converting .wat to .wasm

[features]
debug = []
verbose = []
